config/routes.rb
EmacsKentei::Application.routes.draw do

  get "welcome/newbie"

  resources :problems do
    member do
      post 'answer'
      get 'solvers'
    end
  end
  resources :users

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :choice, :user, :correct

  belongs_to :user
  belongs_to :problem

  def correct?
    correct
  end
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :correct, :description, :title, :wrong1, :wrong2, :wrong3
  self.per_page = 10

  belongs_to :creator, class_name: User
  has_many :answers, :dependent => :destroy
  has_many :solvers, through: :answers, source: :user

  def random_choices
    [correct, wrong1, wrong2, wrong3].shuffle
  end

  def answer_by(user, choice)
    raise "Already answered" if solvers.include?(user)
    answers.create!(user: user, choice: choice, correct: correct == choice)
  end

  def myanswer(user)
    answers.find_by_user_id(user.id) || (raise "Not answered yet")
  end

  def accuracy
    if answers.count > 0
      answers.where(correct: true).count / answers.count.to_f * 100
    else
      0.0
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :uid, :name, :key, :secret

  validates_presence_of :uid, :name, :key, :secret
  validates_uniqueness_of :uid

  has_many :problems, foreign_key: :creator_id
  has_many :answers, :dependent => :destroy
  has_many :answered_problems, through: :answers, source: :problem

  def self.create_with_omniauth(auth)
    create!(uid: auth["uid"], name: auth["info"]["nickname"], key: auth.credentials.token, secret: auth.credentials.secret)
  end

  def self.most_solved(limit = 10)
    User.all.select { | x | x.answers.count > 0 }.sort_by { | x | - x.answers.count }[0...limit]
  end

  def self.most_created(limit = 10)
    User.all.select { | x | x.problems.count > 0 }.sort_by { | x | - x.problems.count }[0...limit]
  end

  def to_s
    name
  end

  def accuracy
    if answers.count > 0
      answers.where(correct: true).count / answers.count.to_f * 100
    else
      0.0
    end
  end

  def solved?(problem)
    answered_problems.include? problem
  end

  def twitter_url
    "https://twitter.com/#!/#{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/problems_controller.rb
# -*- coding: utf-8 -*-
class ProblemsController < ApplicationController

  before_filter :require_login, only: [:new, :create, :answer]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # POST /problems/answer/1
  # POST /problems/answer/1.json
  def answer
    @problem = Problem.find(params[:id])

    @problem.answer_by(current_user, params[:choice])

    respond_to do |format|
      format.html { redirect_to @problem }
      format.json { render json: @problem, status: :answered, location: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])
    @problem.creator = current_user

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: t('helpers.action.create_problem') }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def require_login
    redirect_to '/', notice: t('helpers.action.not_logged_in') unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    if user = User.find_by_uid(auth["uid"])
      login_and_redirect_to(user, "/users/#{ user.id }")
    else
      user = User.create_with_omniauth(auth)
      login_and_redirect_to(user, '/welcome/newbie')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => t('helpers.action.logout')
  end

  private
  def login_and_redirect_to(user, page)
    session[:user_id] = user.id
    redirect_to page, :notice => t('helpers.action.login')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users_solve = User.most_solved
    @users_problem = User.most_created
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def newbie
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def decorate_accuracy(acc)
    color = case acc
            when 0.0...20.0
              "#c82f24"
            when 20.0...40.0
              "#d77612"
            when 40.0...60.0
              "#e6c100"
            when 60.0...80.0
              "#84a620"
            else
              "#228a39"
            end
    %Q{<span style="color: #{color}">#{ "%.1f" % acc }</span>}
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? [yield(:title), "Emacs 検定"].join(" | ") : "Emacs 検定" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Emacs 検定</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "問題一覧", problems_path %></li>
              <li><%= link_to "問題作成", new_problem_path if current_user %></li>
              <li><%= link_to "ランキング", users_path %></li>
            </ul>
            <p class="navbar-text pull-right">
              <% if current_user %>
                ようこそ <%= link_to current_user, current_user %> さん!&nbsp;
                <%= link_to "ログアウト", signout_path %>
              <% else %>
                <%= link_to "Twitter でログイン", "/auth/twitter" %>
              <% end %>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <% if notice %>
            <div class="alert">
              <%= notice %>
             </div>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <center>
          <p>&copy; tomykaira 2012</p>
        </center>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/problems/_form.html.erb
<%= form_for @problem, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :correct, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :correct, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wrong1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wrong1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wrong2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wrong2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wrong3, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wrong3, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                problems_path, :class => 'btn' %>
  </div>
<% end %>

app/views/problems/_list.html.erb
<table class="table table-bordered table-striped problems">
  <tr>
    <th style="width: 30%"><%= Problem.human_attribute_name(:title) %></th>
    <th><%= Problem.human_attribute_name(:description) %></th>
    <th style="white-space:nowrap;"><%= Problem.human_attribute_name(:accuracy) %></th>
    <th style="width: 40px"></th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= link_to problem.title, problem %></td>
    <td><%= problem.description[0..50] %></td>
    <td><%= decorate_accuracy(problem.accuracy).html_safe %></td>
    <td><% if current_user.try(:solved?, problem)%>
          <% if problem.myanswer(current_user).correct? %>
            <i class="icon-ok"></i>
          <% else %>
            <i class="icon-remove"></i>
          <% end %>
        <% else %>
          <%= link_to '解く', problem %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/problems/index.html.erb
<h1>問題一覧</h1>

<p>
  <%= link_to '問題作成', '/problems/new', class: 'btn' if current_user %>
</p>

<%= will_paginate @problems, class: "pagination pagination-centered" %>

<%= render partial: 'list' %>

<%= will_paginate @problems, class: "pagination pagination-centered" %>

app/views/problems/new.html.erb
<%- model_class = @problem.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/problems/show.html.erb
<%- model_class = @problem.class -%>
<h1><%= @problem.title %></h1>

<p>by. <%= link_to @problem.creator, user_path(@problem.creator) %></p>

<p><%= @problem.solvers.count %> 人が解き、<%= @problem.answers.where(correct: true).count %> 人が正解しました。</p>

<p>
  <%= @problem.description %>
</p>

<% if current_user %>
  <% if @problem.solvers.include? current_user %>
    <% answer = @problem.myanswer(current_user) %>
    <div class="alert <%= answer.correct? ? 'alert-success' : 'alert-error' %>">
      あなたの回答: <strong><%= answer.choice %></strong><br />
      正解: <strong><%= @problem.correct %></strong>
    </div>
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://emacs-kentei.heroku.com/" data-text="Emacs 検定で『<%= @problem.title %>』を解きました" data-lang="ja" data-count="none">ツイート</a><br />
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  <% else %>
    <%= form_tag(action: 'answer') do %>
      <% @problem.random_choices.each do |c| %>
        <label class="radio"><%= radio_button_tag 'choice', c, false, class: 'choice' %><%= c %></label>
      <% end %>
      <%= submit_tag "回答", class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% else %>
  <div class="alert alert-warning">
    問題に回答するには、<%= link_to 'twitter アカウントでログイン', '/auth/twitter' %>する必要があります。
  </div>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              problems_path, :class => 'btn'  %>

app/views/users/index.html.erb
<h1>ユーザランキング</h1>
<h2>回答数</h2>
<table class="table table-bordered table-striped problems">
  <tr>
    <th style="width: 30%"><%= User.human_attribute_name(:name) %></th>
    <th>回答数</th>
    <th style="white-space:nowrap;"><%= Problem.human_attribute_name(:accuracy) %></th>
  </tr>

<% @users_solve.each do |u| %>
  <tr>
    <td><%= link_to u, u%></td>
    <td><%= u.answers.count %></td>
    <td><%= decorate_accuracy(u.accuracy).html_safe %></td>
  </tr>
<% end %>
</table>
<h2>問題作成数</h2>
<table class="table table-bordered table-striped problems">
  <tr>
    <th style="width: 30%"><%= User.human_attribute_name(:name) %></th>
    <th>問題作成数</th>
  </tr>

<% @users_problem.each do |u| %>
  <tr>
    <td><%= link_to u, u%></td>
    <td><%= u.problems.count %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<% content_for :title, "#{@user.name} さん" %>
<h1><%= link_to @user.name, @user.twitter_url %> さんのページ</h1>
<h2>正答率: <%= decorate_accuracy(@user.accuracy).html_safe %></h2>
<h2>解いた問題</h2>
<%= @problems = @user.answered_problems; render partial: 'problems/list' %>
<h2>作成した問題</h2>
<%= @problems = @user.problems; render partial: 'problems/list' %>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>Emacs 検定</h1>
  <p>Emacs 検定は、すべての Emacs ユーザが互いに問題を出しあい、高めあう、オープンな最高のフィールドです。</p>
  <p><a href="/auth/twitter" class="btn btn-primary btn-large">Twitter でログイン »</a></p>
</div>

<div class="row">
  <div class="span4">
    <h2>問題を解く</h2>
    <%= link_to image_tag("problems.jpg"), problems_path %>
    <p>Emacs 検定では、他のユーザが作った問題を解くことで、あなたの Emacs 力を高めることができます。周囲の Vim ユーザに「えー Emacs これできんの?」と馬鹿にされたことはありませんか?知識を付けて宗教戦争を制しましょう。</p>
  </div>
  <div class="span4">
    <h2>問題を作る</h2>
    <%= image_tag "create.jpg" %>
    <p>Emacs は奥深い世界です。Vimmer は<%= link_to 'Vim 検定', "http://www.infiniteloop.co.jp/vim/" %>というもので知識を広めているようですが、これは問題を自由に作れるわけではありません。学んだ知識をシェアして、他の Emacs ユーザを支援しましょう。</p>
  </div>
  <div class="span4">
    <h2>Fork me on Github!</h2>
    <%= link_to image_tag("github.png"), "https://github.com/tomykaira/emacs_kentei" %>
    <p>本プロジェクトのソースコードはすべて github 上でシェアされています。プロジェクトは発展途上なので、いろいろな機能追加を募集しています。こんな機能が欲しい、という提案も、Issue から御気軽にどうそ。</p>
  </div>
</div>

app/views/welcome/newbie.html.erb
<% content_for :title, 'ようこそ' %>
<h2>Twitter で始めたことをつぶやきましょう!</h2>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://emacs-kentei.heroku.com/" data-text="Emacs 検定 始めました" data-lang="ja" data-size="large" data-related="tomy_kaira">ツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<h2>問題を解きましょう!</h2>
<p>まずは問題を解いてみましょう。<br />
他のユーザが登録した問題がたくさんあります。</p>
<p>間違えても大丈夫。答えが表示されるので、それをみて勉強してください。</p>
<%= link_to '問題一覧', '/problems', class: 'btn' %>
<h2>問題を作りましょう</h2>
<p>他の問題を見て、雰囲気がわかったら、ぜひ問題を自分で作ってみてください。<br />
ニッチな問題なら、他の Emacs 上級者にとっても勉強になります。</p>
<%= link_to '問題を作る', '/problems/new', class: 'btn' %>